"""Generate user-owned Runpod Flash endpoint adapters."""

from __future__ import annotations

import re
from pathlib import Path


ENV_NAME_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def validate_endpoint_env_name(name: str) -> str:
    if not ENV_NAME_PATTERN.fullmatch(name):
        raise ValueError(f"invalid endpoint environment variable name: {name!r}")
    return name


def parse_endpoint_env(
    env: list[str],
    env_from: list[str],
) -> tuple[dict[str, str], list[str]]:
    literals: dict[str, str] = {}
    for item in env:
        if "=" not in item:
            raise ValueError("--env values must use NAME=value")
        name, value = item.split("=", 1)
        name = validate_endpoint_env_name(name)
        if name in literals:
            raise ValueError(f"duplicate endpoint environment variable: {name}")
        literals[name] = value

    from_names: list[str] = []
    seen_from: set[str] = set()
    for item in env_from:
        name = validate_endpoint_env_name(item)
        if name in seen_from:
            raise ValueError(f"duplicate endpoint environment variable: {name}")
        if name in literals:
            raise ValueError(
                f"endpoint environment variable set by both --env and --env-from: {name}"
            )
        seen_from.add(name)
        from_names.append(name)

    return literals, from_names


def render_endpoint_env_argument(env: dict[str, str] | None, env_from: list[str] | None) -> str:
    literal_env = dict(env or {})
    from_env = list(env_from or [])
    if not literal_env and not from_env:
        return ""

    for name in literal_env:
        validate_endpoint_env_name(name)
    seen_from: set[str] = set()
    for name in from_env:
        validate_endpoint_env_name(name)
        if name in seen_from:
            raise ValueError(f"duplicate endpoint environment variable: {name}")
        if name in literal_env:
            raise ValueError(f"endpoint environment variable set by both env and env_from: {name}")
        seen_from.add(name)

    lines = ["    env={"]
    for name, value in literal_env.items():
        lines.append(f"        {name!r}: {value!r},")
    for name in from_env:
        lines.append(f"        {name!r}: os.environ[{name!r}],")
    lines.append("    },")
    return "\n".join(lines)


def render_runpod_endpoint(
    *,
    runner_import: str,
    endpoint_name: str,
    gpu: str,
    workers_min: int,
    workers_max: int,
    idle_timeout: int,
    dependencies: list[str],
    system_dependencies: list[str],
    env: dict[str, str] | None = None,
    env_from: list[str] | None = None,
    function_name: str = "run_flashburst_job",
) -> str:
    if ":" not in runner_import:
        raise ValueError("runner import must be in module:function format")
    module_name, function_attr = runner_import.split(":", 1)
    dependencies_literal = repr(dependencies)
    system_dependencies_literal = repr(system_dependencies)
    env_argument = render_endpoint_env_argument(env, env_from)
    return f'''"""Runpod Flash endpoint generated by Flashburst.

This file is owned by the workload project. It intentionally does not import
Flashburst; remote execution only needs JSON input, params, and optional
presigned artifact URLs.
"""

import json
import os
import tempfile
from pathlib import Path
from urllib.request import Request, urlopen

from runpod_flash import Endpoint, GpuGroup

from {module_name} import {function_attr} as run_job

ENDPOINT_WRAPPER_VERSION = "flashburst-artifacts-v1"


def endpoint_metrics() -> dict:
    return {{
        "endpoint_wrapper_version": ENDPOINT_WRAPPER_VERSION,
        "endpoint_flash_source_fingerprint": os.environ.get("_FLASH_SOURCE_FINGERPRINT"),
        "endpoint_runpod_pod_id": os.environ.get("RUNPOD_POD_ID"),
    }}


def params_with_wrapper_context(params: dict | None) -> dict:
    merged = dict(params or {{}})
    merged["wrapper_context"] = endpoint_metrics()
    return merged


def safe_path_component(value: str) -> str:
    safe = "".join(char if char.isalnum() or char in "._-" else "-" for char in value)
    return safe.strip("._-") or "file"


def download_input_files(payload: dict, tmp_path: Path, input_payload: dict) -> int:
    downloaded = 0
    for file_spec in payload.get("input_files") or []:
        if not isinstance(file_spec, dict):
            raise ValueError("input_files entries must be objects")
        field = file_spec.get("field")
        get_url = file_spec.get("get_url")
        if not field or not get_url:
            raise ValueError("input_files entries require field and get_url")
        filename = Path(str(file_spec.get("filename") or field)).name
        destination = tmp_path / "inputs" / safe_path_component(str(field)) / filename
        destination.parent.mkdir(parents=True, exist_ok=True)
        request = Request(str(get_url), headers={{"User-Agent": "flashburst-endpoint/1"}})
        with urlopen(request, timeout=300) as response:
            destination.write_bytes(response.read())
        input_payload[str(field)] = str(destination)
        downloaded += 1
    return downloaded


def upload_output_file(payload: dict, output_path: Path) -> bool:
    output_file = payload.get("output_file")
    if not output_file:
        return False
    if not output_path.exists():
        return False
    if not isinstance(output_file, dict) or not output_file.get("put_url"):
        raise ValueError("output_file requires put_url")
    media_type = str(output_file.get("media_type") or "application/octet-stream")
    request = Request(
        str(output_file["put_url"]),
        data=output_path.read_bytes(),
        headers={{
            "Content-Type": media_type,
            "User-Agent": "flashburst-endpoint/1",
        }},
        method="PUT",
    )
    with urlopen(request, timeout=300) as response:
        response.read()
    return True


@Endpoint(
    name="{endpoint_name}",
    gpu=GpuGroup.{gpu},
    workers=({workers_min}, {workers_max}),
    idle_timeout={idle_timeout},
    dependencies={dependencies_literal},
    system_dependencies={system_dependencies_literal},
{env_argument}
)
async def {function_name}(**payload: dict) -> dict:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        input_path = tmp_path / "input.json"
        output_path = tmp_path / "result.jsonl"
        input_payload = dict(payload.get("input") or {{}})
        downloaded_input_files = download_input_files(payload, tmp_path, input_payload)
        input_path.write_text(
            json.dumps(input_payload, sort_keys=True, separators=(",", ":")),
            encoding="utf-8",
        )
        result = run_job(
            input_path,
            output_path,
            params_with_wrapper_context(payload.get("params")),
        )
        uploaded_output_file = upload_output_file(payload, output_path)
        output_text = (
            None
            if uploaded_output_file
            else output_path.read_text(encoding="utf-8")
            if output_path.exists()
            else None
        )
        metrics = result.get("metrics", {{}}) if isinstance(result, dict) else {{}}
        return {{
            "status": result.get("status", "succeeded") if isinstance(result, dict) else "succeeded",
            "output_text": output_text,
            "output_media_type": "application/x-ndjson",
            "metrics": {{
                **endpoint_metrics(),
                "artifact_input_files": downloaded_input_files,
                "artifact_output_uploaded": uploaded_output_file,
                **metrics,
            }},
            "error": result.get("error") if isinstance(result, dict) else None,
        }}
'''


def scaffold_runpod_endpoint(
    *,
    output: Path,
    runner_import: str,
    endpoint_name: str,
    gpu: str,
    workers_min: int,
    workers_max: int,
    idle_timeout: int,
    dependencies: list[str],
    system_dependencies: list[str],
    env: dict[str, str] | None = None,
    env_from: list[str] | None = None,
) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_runpod_endpoint(
            runner_import=runner_import,
            endpoint_name=endpoint_name,
            gpu=gpu,
            workers_min=workers_min,
            workers_max=workers_max,
            idle_timeout=idle_timeout,
            dependencies=dependencies,
            system_dependencies=system_dependencies,
            env=env,
            env_from=env_from,
        ),
        encoding="utf-8",
    )
    return output
