"""Generate user-owned Runpod Flash endpoint adapters."""

from __future__ import annotations

from pathlib import Path


def render_runpod_endpoint(
    *,
    runner_import: str,
    endpoint_name: str,
    gpu: str,
    workers_min: int,
    workers_max: int,
    idle_timeout: int,
    dependencies: list[str],
    system_dependencies: list[str],
    function_name: str = "run_flashburst_job",
) -> str:
    if ":" not in runner_import:
        raise ValueError("runner import must be in module:function format")
    module_name, function_attr = runner_import.split(":", 1)
    dependencies_literal = repr(dependencies)
    system_dependencies_literal = repr(system_dependencies)
    return f'''"""Runpod Flash endpoint generated by Flashburst.

This file is owned by the workload project. It intentionally does not import
Flashburst; remote execution only needs the envelope JSON shape and the user's
file-based runner.
"""

import hashlib
import os
import tempfile
from pathlib import Path

import httpx
from runpod_flash import Endpoint, GpuGroup

from {module_name} import {function_attr} as run_job

ENDPOINT_WRAPPER_VERSION = "flashburst-endpoint-scaffold-v3-buffered-upload-diagnostics"


def find_grant(envelope: dict, method: str) -> dict:
    for grant in envelope.get("artifact_grants", []):
        if grant.get("method") == method:
            return grant
    raise ValueError(f"missing {{method}} artifact grant")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


async def download(url: str, destination: Path) -> None:
    async with httpx.AsyncClient(timeout=120) as client:
        async with client.stream("GET", url) as response:
            response.raise_for_status()
            with destination.open("wb") as handle:
                async for chunk in response.aiter_bytes():
                    handle.write(chunk)


class UploadFailed(RuntimeError):
    def __init__(self, message: str, diagnostics: dict):
        super().__init__(message)
        self.diagnostics = diagnostics


def endpoint_metrics() -> dict:
    return {{
        "endpoint_wrapper_version": ENDPOINT_WRAPPER_VERSION,
        "endpoint_flash_source_fingerprint": os.environ.get("_FLASH_SOURCE_FINGERPRINT"),
        "endpoint_runpod_pod_id": os.environ.get("RUNPOD_POD_ID"),
    }}


def params_with_wrapper_context(params: dict | None) -> dict:
    merged = dict(params or {{}})
    merged["wrapper_context"] = endpoint_metrics()
    return merged


async def upload(url: str, source: Path, content_type: str | None) -> dict:
    content = source.read_bytes()
    headers = {{"Content-Length": str(source.stat().st_size)}}
    if content_type:
        headers["Content-Type"] = content_type
    diagnostics = {{
        "upload_strategy": "buffered-bytes-put",
        "upload_content_length": headers["Content-Length"],
        "upload_content_type": content_type,
    }}
    async with httpx.AsyncClient(timeout=120) as client:
        response = await client.put(url, content=content, headers=headers)
        diagnostics["upload_response_status_code"] = response.status_code
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as exc:
            raise UploadFailed(str(exc), diagnostics) from exc
    return diagnostics


@Endpoint(
    name="{endpoint_name}",
    gpu=GpuGroup.{gpu},
    workers=({workers_min}, {workers_max}),
    idle_timeout={idle_timeout},
    dependencies={dependencies_literal},
    system_dependencies={system_dependencies_literal},
)
async def {function_name}(**envelope: dict) -> dict:
    read_grant = find_grant(envelope, "GET")
    write_grant = find_grant(envelope, "PUT")
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        input_path = tmp_path / "input"
        output_path = tmp_path / "result.jsonl"
        await download(read_grant["url"], input_path)
        result = run_job(
            input_path,
            output_path,
            params_with_wrapper_context(envelope.get("params")),
        )
        try:
            upload_metrics = await upload(
                write_grant["url"],
                output_path,
                write_grant.get("content_type"),
            )
        except UploadFailed as exc:
            return {{
                "status": "failed",
                "output_artifacts": [],
                "metrics": {{
                    **endpoint_metrics(),
                    **(result.get("metrics", {{}}) if isinstance(result, dict) else {{}}),
                    **exc.diagnostics,
                }},
                "logs_uri": result.get("logs_uri") if isinstance(result, dict) else None,
                "error": str(exc),
            }}

        return {{
            "status": result.get("status", "succeeded"),
            "output_artifacts": [
                {{
                    "uri": write_grant["artifact_uri"],
                    "media_type": write_grant.get("content_type") or "application/x-ndjson",
                    "storage": "s3",
                    "sha256": sha256_file(output_path),
                    "size_bytes": output_path.stat().st_size,
                    "producer_job_id": envelope.get("job_id"),
                }}
            ],
            "metrics": {{
                **endpoint_metrics(),
                **result.get("metrics", {{}}),
                **upload_metrics,
            }},
            "logs_uri": result.get("logs_uri"),
            "error": result.get("error"),
        }}
'''


def scaffold_runpod_endpoint(
    *,
    output: Path,
    runner_import: str,
    endpoint_name: str,
    gpu: str,
    workers_min: int,
    workers_max: int,
    idle_timeout: int,
    dependencies: list[str],
    system_dependencies: list[str],
) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_runpod_endpoint(
            runner_import=runner_import,
            endpoint_name=endpoint_name,
            gpu=gpu,
            workers_min=workers_min,
            workers_max=workers_max,
            idle_timeout=idle_timeout,
            dependencies=dependencies,
            system_dependencies=system_dependencies,
        ),
        encoding="utf-8",
    )
    return output
